### ISSUE TITLE
Implement logging on eesectors 

### ISSUE THREAD

**Issue by mammykins** [DCMSstats/eesectors#105]
http://adv-r.had.co.nz/beyond-exception-handling.html

if you have a chance, could you have a look at this, and maybe implement some logging on eesectors as an example? 

https://cran.rstudio.com/web/packages/futile.logger/index.html

https://github.com/zatonovo/futile.logger

**Comment by ivyleavedtoadflax** [comment]
Great stuff @mammykins in #106. We should aim to roll out this as a consistent method across the whole package.
