### ISSUE TITLE
example_working_file() is not exported and doesn't work as expected

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [DCMSstats/eesectors#119]
I'm a bit confused by this function. It's not currently exported, so I added `@export` to make it available as a user, but it does not return the full path of the test data:

```
> library(eesectors)
> example_working_file()
[1] "example_working_file.xlsx"
> file.exists(example_working_file())
[1] FALSE
```

Does this want to return the real and full path of the file, so it can be passed to other functions?

**Comment by maxwell8888** [comment]
sorry I didn't see this. it should work like this:
path <- example_working_file("example_working_file.xlsx")
