### ISSUE TITLE
No more tibbles

### ISSUE THREAD

**Issue by DCMSstats** [DCMSstats/eesectors#86]
Hi,

Not entirely sure if it's something I've done but loaded data seems to have stopped being tibbles and are now just data frames on my Macbook - but remains a tibble when I try from a different (OSX) computer. Any idea why this might be happening?

Niall

**Comment by ivyleavedtoadflax** [comment]
Hey! Can you post a code snippet here as an example. If `dplyr` is not loaded when you run the code, I think this could happen.

**Comment by DCMSstats** [comment]
That appears to be the problem! I was removing the Tourism SIC from DCMS_sectors as it's not used in the GVA and is causing issues with the employment functions I'm writing but didn't load dplyr - sorry for such a trivial issue!
